library(Seurat)
library(ggplot2)
library(patchwork)
library(dplyr)
library(cowplot)
library(scater)
library(scran)
library(BiocParallel)
library(BiocNeighbors)
library(nloptr)
library(hdf5r)

ShamA<- readRDS("~/ShamA.rds")
ShamB<- readRDS("~/ShamB.rds")
IRH4<- readRDS("~/IRH4.rds")
IRH12<- readRDS("~/IRH12.rds")
IRD1<- readRDS("~/IRD1.rds")
IRD5A<- readRDS("~/IRG5A.rds")
IRD5B<- readRDS("~/IRD5B.rds")
IRD5C<- readRDS("~/IRD5C.rds")
IRD14<- readRDS("~/IRD14.rds")
IRD28<- readRDS("~/IRD28.rds")

VlnPlot(ShamA, features = c("nFeature_RNA", "nCount_RNA", "percent.mito"))
VlnPlot(ShamB, features = c("nFeature_RNA", "nCount_RNA", "percent.mito"))
VlnPlot(IRH4, features = c("nFeature_RNA", "nCount_RNA", "percent.mito"))
VlnPlot(IRH12, features = c("nFeature_RNA", "nCount_RNA", "percent.mito"))
VlnPlot(IRD1, features = c("nFeature_RNA", "nCount_RNA", "percent.mito"))
VlnPlot(IR5A, features = c("nFeature_RNA", "nCount_RNA", "percent.mito"))
VlnPlot(IRD5B, features = c("nFeature_RNA", "nCount_RNA", "percent.mito"))
VlnPlot(IRD5C, features = c("nFeature_RNA", "nCount_RNA", "percent.mito"))
VlnPlot(IRD14, features = c("nFeature_RNA", "nCount_RNA", "percent.mito"))
VlnPlot(IRD28, features = c("nFeature_RNA", "nCount_RNA", "percent.mito"))

IR<- readRDS("~/IR.rds")
VlnPlot(IR, features = c("nFeature_RNA", "nCount_RNA", "percent.mito"))
