library(Seurat)
library(ggplot2)
library(patchwork)
library(dplyr)
library(cowplot)
library(scater)
library(scran)
library(BiocParallel)
library(BiocNeighbors)
library(nloptr)
library(hdf5r)
library(plot1cell)

IR<- readRDS("~/IR.rds")

complex_dotplot_single(seu_obj = IR,feature = c("Lcn2"),groups="group")
complex_dotplot_single(seu_obj = IR,feature = c("Havcr1"),groups="group")
complex_dotplot_single(seu_obj = IR,feature = c("Il1b"),groups="group")
complex_dotplot_single(seu_obj = IR,feature = c("Fn1"),groups="group")
complex_dotplot_single(seu_obj = IR,feature = c("Col1a2"),groups="group")
complex_dotplot_single(seu_obj = IR,feature = c("Col1a1"),groups="group")
